### ISSUE TITLE
Mac OS build is failing due to ACTION macro problems

### ISSUE THREAD

**Issue by njh** [columbia-irt/rtptools#76]
```
~/Projects/rtptools(master) $ cc --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
~/Projects/rtptools(master) $ make
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c hpt.c
hpt.c:47:5: warning: no previous prototype for function 'hpt'
      [-Wmissing-prototypes]
int hpt(char *h, struct sockaddr *sa, unsigned char *ttl)
    ^
1 warning generated.
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c host2ip.c
host2ip.c:47:16: warning: no previous prototype for function 'host2ip'
      [-Wmissing-prototypes]
struct in_addr host2ip(char *host)
               ^
host2ip.c:56:42: warning: comparison of integers of different signs: 'in_addr_t'
      (aka 'unsigned int') and 'int' [-Wsign-compare]
  else if ((in.s_addr = inet_addr(host)) != -1) {
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^  ~~
2 warnings generated.
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c rd.c
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c rtpdump.c
rtpdump.c:168:11: warning: passing 'const char [1]' to parameter of type
      'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    usage("");
          ^~
rtpdump.c:120:25: note: passing argument to parameter 'argv0' here
static void usage(char *argv0)
                        ^
rtpdump.c:173:11: warning: passing 'const char [1]' to parameter of type
      'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    usage("");
          ^~
rtpdump.c:120:25: note: passing argument to parameter 'argv0' here
static void usage(char *argv0)
                        ^
rtpdump.c:171:28: warning: comparison of integers of different signs:
      'in_addr_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
  if (sin->sin_addr.s_addr == -1) {
      ~~~~~~~~~~~~~~~~~~~~ ^  ~~
rtpdump.c:273:12: warning: returning 'const char *' from a function with result
      type 'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    return r->version == RTP_VERSION ? "RTP" : "VATD";
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rtpdump.c:277:12: warning: returning 'const char *' from a function with result
      type 'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    return r->common.version == RTP_VERSION ? "RTCP" : "VATC";
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rtpdump.c:343:43: warning: format specifies type 'unsigned long' but the
      argument has type 'uint32_t' (aka 'unsigned int') [-Wformat]
      fprintf(out, "csrc[%d]=0x%0lx ", i, r->csrc[i]);
                               ~~~~       ^~~~~~~~~~
                               %0x
rtpdump.c:376:46: warning: format specifies type 'long' but the argument has
      type '__darwin_suseconds_t' (aka 'int') [-Wformat]
      (v->flags ? -now.tv_sec : now.tv_sec), now.tv_usec,
                                             ^~~~~~~~~~~
rtpdump.c:381:42: warning: format specifies type 'long' but the argument has
      type '__darwin_suseconds_t' (aka 'int') [-Wformat]
      (r->m ? -now.tv_sec : now.tv_sec), now.tv_usec,
                                         ^~~~~~~~~~~
rtpdump.c:399:24: warning: initializing 'char *' with an expression of type
      'const char [4]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_END,    "end"}, 
                       ^~~~~
rtpdump.c:400:24: warning: initializing 'char *' with an expression of type
      'const char [6]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_CNAME,  "CNAME"},
                       ^~~~~~~
rtpdump.c:401:24: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_NAME,   "NAME"},
                       ^~~~~~
rtpdump.c:402:24: warning: initializing 'char *' with an expression of type
      'const char [6]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_EMAIL,  "EMAIL"},
                       ^~~~~~~
rtpdump.c:403:24: warning: initializing 'char *' with an expression of type
      'const char [6]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_PHONE,  "PHONE"},
                       ^~~~~~~
rtpdump.c:404:24: warning: initializing 'char *' with an expression of type
      'const char [4]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_LOC,    "LOC"},
                       ^~~~~
rtpdump.c:405:24: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_TOOL,   "TOOL"},
                       ^~~~~~
rtpdump.c:406:24: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_NOTE,   "NOTE"},
                       ^~~~~~
rtpdump.c:407:24: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {RTCP_SDES_PRIV,   "PRIV"},
                       ^~~~~~
rtpdump.c:408:24: warning: initializing 'char *' with an expression of type
      'const char [7]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {11,               "SOURCE"},
                       ^~~~~~~~
rtpdump.c:393:6: warning: no previous prototype for function 'member_sdes'
      [-Wmissing-prototypes]
void member_sdes(FILE *out, member_t m, rtcp_sdes_type_t t, char *b, int len)
     ^
rtpdump.c:635:29: warning: format specifies type 'long' but the argument has
      type '__darwin_suseconds_t' (aka 'int') [-Wformat]
                now.tv_sec, now.tv_usec, parse_type(ctrl, packet->p.data),
                            ^~~~~~~~~~~
rtpdump.c:648:29: warning: format specifies type 'long' but the argument has
      type '__darwin_suseconds_t' (aka 'int') [-Wformat]
                now.tv_sec, now.tv_usec, parse_type(ctrl, packet->p.data),
                            ^~~~~~~~~~~
rtpdump.c:581:6: warning: no previous prototype for function 'packet_handler'
      [-Wmissing-prototypes]
void packet_handler(FILE *out, t_format format, int trunc,
     ^
rtpdump.c:667:6: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"dump",    F_dump},
     ^~~~~~
rtpdump.c:668:6: warning: initializing 'char *' with an expression of type
      'const char [7]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"header",  F_header},
     ^~~~~~~~
rtpdump.c:669:6: warning: initializing 'char *' with an expression of type
      'const char [4]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"hex",     F_hex},
     ^~~~~
rtpdump.c:670:6: warning: initializing 'char *' with an expression of type
      'const char [5]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"rtcp",    F_rtcp},
     ^~~~~~
rtpdump.c:671:6: warning: initializing 'char *' with an expression of type
      'const char [6]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"short",   F_short},
     ^~~~~~~
rtpdump.c:672:6: warning: initializing 'char *' with an expression of type
      'const char [8]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"payload", F_payload},
     ^~~~~~~~~
rtpdump.c:673:6: warning: initializing 'char *' with an expression of type
      'const char [6]' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
    {"ascii",   F_ascii},
     ^~~~~~~
29 warnings generated.
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -o rtpdump hpt.o host2ip.o                     rd.o rtpdump.o 
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c notify.c
notify.c:71:6: warning: no previous prototype for function 'check_clr_fd'
      [-Wmissing-prototypes]
void check_clr_fd(void)
     ^
notify.c:141:13: warning: no previous prototype for function
      'notify_set_itimer_func' [-Wmissing-prototypes]
Notify_func notify_set_itimer_func(
            ^
notify.c:208:63: warning: format specifies type 'unsigned long' but the argument
      has type '__darwin_suseconds_t' (aka 'int') [-Wformat]
      fprintf(stderr, "Timeout: %lu.%06lu\n", timeout.tv_sec, timeout.tv_usec);
                                    ~~~~~                     ^~~~~~~~~~~~~~~
                                    %06d
3 warnings generated.
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c multimer.c
multimer.c:95:6: warning: no previous prototype for function 'timer_check'
      [-Wmissing-prototypes]
void timer_check(void)
     ^
multimer.c:119:17: warning: no previous prototype for function 'timer_set'
      [-Wmissing-prototypes]
struct timeval *timer_set(struct timeval *interval, 
                ^
multimer.c:191:17: warning: no previous prototype for function 'timer_get'
      [-Wmissing-prototypes]
struct timeval *timer_get(struct timeval *timeout)
                ^
multimer.c:231:5: warning: no previous prototype for function 'timer_pending'
      [-Wmissing-prototypes]
int timer_pending(void)
    ^
4 warnings generated.
cc -g -W -Wall -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wno-unused-parameter -c rtpplay.c
In file included from rtpplay.c:52:
./hsearch.h:43:16: error: redefinition of 'entry'
typedef struct entry {
               ^
/usr/include/search.h:16:16: note: previous definition is here
typedef struct entry {
               ^
In file included from rtpplay.c:52:
./hsearch.h:46:3: error: typedef redefinition with different types ('struct
      (anonymous struct at ./hsearch.h:43:16)' vs 'struct entry')
} ENTRY;
  ^
/usr/include/search.h:19:3: note: previous definition is here
} ENTRY;
  ^
In file included from rtpplay.c:52:
./hsearch.h:49:9: error: redefinition of enumerator 'FIND'
        FIND, ENTER
        ^
/usr/include/search.h:22:2: note: previous definition is here
        FIND, ENTER
        ^
In file included from rtpplay.c:52:
./hsearch.h:49:15: error: redefinition of enumerator 'ENTER'
        FIND, ENTER
              ^
/usr/include/search.h:22:8: note: previous definition is here
        FIND, ENTER
              ^
In file included from rtpplay.c:52:
./hsearch.h:50:3: error: typedef redefinition with different types
      ('enum ACTION' vs 'enum ACTION')
} ACTION;
  ^
/usr/include/search.h:23:3: note: previous definition is here
} ACTION;
  ^
rtpplay.c:361:52: warning: passing 'char *' to parameter of type
      'unsigned char *' converts between pointers to integer types with
      different sign [-Wpointer-sign]
    if (hpt(argv[optind], (struct sockaddr *)&sin, &ttl) < 0) {
                                                   ^~~~
rtpplay.c:317:63: note: passing argument to parameter 'ttl' here
  extern int hpt(char *h, struct sockaddr *sa, unsigned char *ttl);
                                                              ^
rtpplay.c:365:29: warning: comparison of integers of different signs:
      'in_addr_t' (aka 'unsigned int') and 'int' [-Wsign-compare]
    if (sin.sin_addr.s_addr == -1) {
        ~~~~~~~~~~~~~~~~~~~ ^  ~~
2 warnings and 5 errors generated.
make: *** [rtpplay.o] Error 1
```

**Comment by janstary** [comment]
Thanks for the report.

This looks exactly like the breakage introduced in https://github.com/columbia-irt/rtptools/commit/b267e8c08d55ad0793c097fe3b6e49df540aed0b and fixed in https://github.com/columbia-irt/rtptools/commit/61f778c59143feff4612c7aa559535c94e9945ed .
It has recently been merged - can you please try with the current master?

I wonder why it failed on MacOS but did not fail on Ubuntu.
An explanation would be if Ubuntu does not have `hsearch`,
in which case the bundled implementaion was used without the conflict described here.

**Comment by njh** [comment]
Yup, master is working on MacOS again.

**Comment by njh** [comment]
MacOS building successfully in Travis too:
https://travis-ci.org/njh/rtptools/builds/360217240
